/*
 * This Java source file was generated by the Gradle 'init' task.
 
package com.weather;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        WeatherApplication classUnderTest = new WeatherApplication();
       // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
*/